"""add speaker session registration tables

Revision ID: 31828c1fceaf
Revises: 60d39c4e5609
Create Date: 2026-05-23 08:51:49.351407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31828c1fceaf'
down_revision: Union[str, None] = '60d39c4e5609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_name'), 'speaker', ['name'], unique=False)
    op.create_table('registration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_registration_event_user')
    )
    op.create_index(op.f('ix_registration_event_id'), 'registration', ['event_id'], unique=False)
    op.create_index(op.f('ix_registration_user_id'), 'registration', ['user_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('speaker_id', sa.Uuid(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_event_id'), 'session', ['event_id'], unique=False)
    op.create_index(op.f('ix_session_speaker_id'), 'session', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_session_start_time'), 'session', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_start_time'), table_name='session')
    op.drop_index(op.f('ix_session_speaker_id'), table_name='session')
    op.drop_index(op.f('ix_session_event_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_registration_user_id'), table_name='registration')
    op.drop_index(op.f('ix_registration_event_id'), table_name='registration')
    op.drop_table('registration')
    op.drop_index(op.f('ix_speaker_name'), table_name='speaker')
    op.drop_table('speaker')
    # ### end Alembic commands ###
